### ISSUE TITLE
first five characters of all paths cut on first fresh sync

### ISSUE THREAD

**Issue by mcmtroffaes** [abraunegg/onedrive#17]
I just tried to run version 1.1.3, and I observed that the client downloads all files but cuts the first five characters from every path for some reason. Once it got all those files, the client started to upload the files but with the cut paths. This was on a fresh install and a fresh first sync, where I started the client with "./onedrive --monitor". The cliend was compiled with the LLVM D compiler on Fedora.

I retested a fresh first sync with version 1.1.2, and the issue did not occur on that older version. I noticed from the logs that there have been some changes for OneDrive Business and this is on such an account. Note that no paths exceeded the 256 character limit. The issue may or may not be related to this.

**Comment by abraunegg** [comment]
Interesting ... can you provide some `--verbose` logs for both versions & some file system details including full path names what they should be & what they are being truncated to?

**Comment by abraunegg** [comment]
I think I have a reproducer here locally now ..

**Comment by abraunegg** [comment]
Most likely cause is the 2 changes that were to resolve #11

Will have to look at this more closely.

**Comment by crayiii** [comment]
Same issue.  Fresh install using onedrive for business

**Comment by abraunegg** [comment]
Back out to v1.1.2 where this issue is not present. Issue relates to changes as part of fixing #11

**Comment by mcmtroffaes** [comment]
Unfortunately, the current master still exhibits the problem. I'll try to do a git bisect to find the offending commit. For now, here's a log when running with v1.1.3:

```
2018-Jun-13 07:29:29.453058 Loading config ...
2018-Jun-13 07:29:29.4545118 Using Config Dir: /home/<username>/.config/onedrive
2018-Jun-13 07:29:29.4547555 No config file found, using defaults
2018-Jun-13 07:29:29.4548675 Initializing the OneDrive API ...
2018-Jun-13 07:29:31.6218167 Opening the item database ...
2018-Jun-13 07:29:31.6367666 All operations will be performed in: /home/<username>/OneDrive
2018-Jun-13 07:29:31.6372425 Initializing the Synchronization Engine ...
2018-Jun-13 07:29:37.0470338 Account Type: business
2018-Jun-13 07:29:37.0474256 Default Drive ID: XXX
2018-Jun-13 07:29:37.0496867 Default Root ID: XXX
2018-Jun-13 07:29:37.049826 Remaining Free Space: XXX
2018-Jun-13 07:29:37.0498882 Fetching details for OneDrive Root
2018-Jun-13 07:29:37.496909 OneDrive Root does not exist in the database. We need to add it.
2018-Jun-13 07:29:37.5013783 Added OneDrive Root to the local database
2018-Jun-13 07:29:37.5015843 Initializing monitor ...
2018-Jun-13 07:29:37.5018013 Monitor directory: .
2018-Jun-13 07:30:23.1719868 Applying changes of Path ID: XXX
2018-Jun-13 07:30:38.6713946 Downloading ct/a.pdf... done.
2018-Jun-13 07:30:47.2454682 Downloading ct/b.pdf... done.
2018-Jun-13 07:30:52.6565733 Downloading ct/c.pdf... done.
```

The folder name is supposed to be "project" (as you can see it has been cut to "ct"). There are more files but I stopped the sync there. With v1.1.2:

```
2018-Jun-13 07:41:29.8474895 Loading config ...
2018-Jun-13 07:41:29.8476995 Using Config Dir: /home/<username>/.config/onedrive
2018-Jun-13 07:41:29.8478595 No config file found, using defaults
2018-Jun-13 07:41:29.8479639 Initializing the OneDrive API ...
2018-Jun-13 07:41:30.6049734 Opening the item database ...
2018-Jun-13 07:41:30.6234861 All operations will be performed in: /home/<username>/OneDrive
2018-Jun-13 07:41:30.6241014 Initializing the Synchronization Engine ...
2018-Jun-13 07:41:34.7158354 Account Type: business
2018-Jun-13 07:41:34.7162445 Default Drive ID: XXX
2018-Jun-13 07:41:34.716443 Default Root ID: XXX
2018-Jun-13 07:41:34.7166614 Remaining Free Space: XXX
2018-Jun-13 07:41:34.716757 Fetching details for OneDrive Root
2018-Jun-13 07:41:35.1595974 OneDrive Root does not exist in the database. We need to add it.
2018-Jun-13 07:41:35.1648035 Added OneDrive Root to the local database
2018-Jun-13 07:41:35.1651406 Initializing monitor ...
2018-Jun-13 07:41:35.1655225 Monitor directory: .
2018-Jun-13 07:42:21.6919785 Applying changes of Path ID: XXX
2018-Jun-13 07:44:26.5920989 Timeout was reached on handle 11B3B80
2018-Jun-13 07:44:26.5922875 Applying changes of Path ID: XXX
2018-Jun-13 07:44:30.7872928 Creating directory project
2018-Jun-13 07:44:51.5253221 Downloading project/a.pdf... done.
2018-Jun-13 07:45:12.3340137 Downloading project/b.pdf... done.
2018-Jun-13 07:45:16.7327604 Downloading project/c.pdf... done.
```

**Comment by mcmtroffaes** [comment]
... and git bisect tells me that the bug was introduced in https://github.com/abraunegg/onedrive/commit/e7267e597b34d83b7aa0ab0203b7c494bb8c2ff0 - I hope this helps. Let me know if you need me to run any extra checks.

**Comment by abraunegg** [comment]
What I have done is already reverted the last 2 commits which were to resolve #11 - which I have re-opened ..

As I can reproduce here - will be working on this tonight till this is resolved / #11 is fixed without introducing this behaviour .. which doesn't make sense as to how or why it is occuring .. but it is ..

**Comment by mcmtroffaes** [comment]
Oh yes, I hadn't seen the last revert yet when I started my tests. Thanks for doing so, I can confirm that the current master no longer contains the bug, so I think this issue can be closed.

**Comment by abraunegg** [comment]
Glad that this issue is resolved .. but still trying to work out the root cause in the #11 fixes ... 

Leave this case open until I fix #11 so that this all can be validated together.

**Comment by mcmtroffaes** [comment]
Sure, I'll be ready to run some further tests. I've now looked at the code in a bit more detail as well and couldn't see an obvious culprit... I'm sorry I can't be more helpful for now.

**Comment by abraunegg** [comment]
@mcmtroffaes 

Are you able to help testing the following?

Clone the latest git master & then manually apply following patch before I sync this in:

```
diff -uNr original/onedrive.d modified/onedrive.d
--- original/onedrive.d 2018-06-13 16:35:52.000000000 +1000
+++ modified/onedrive.d 2018-06-13 18:48:00.000000000 +1000
@@ -190,12 +190,12 @@
 
        // Return the details of the specified id
        // https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get
-       JSONValue getPathDetailsById(const(char)[] id)
+       JSONValue getPathDetailsById(string driveId, const(char)[] id)
        {
                checkAccessTokenExpired();
                const(char)[] url;
-               //              string itemByIdUrl = "https://graph.microsoft.com/v1.0/me/drive/items/";
-               url = itemByIdUrl ~ id;
+               //              string driveByIdUrl = "https://graph.microsoft.com/v1.0/drives/";
+               url = driveByIdUrl ~ driveId ~ "/items/" ~ id;
                url ~= "?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference";
                return get(url);
        }
diff -uNr original/sync.d modified/sync.d
--- original/sync.d     2018-06-13 16:35:52.000000000 +1000
+++ modified/sync.d     2018-06-13 22:39:26.000000000 +1000
@@ -58,7 +58,13 @@
                item.mtime = SysTime(0);
        } else {
                // Item is not in a deleted state
-               item.mtime = SysTime.fromISOExtString(driveItem["fileSystemInfo"]["lastModifiedDateTime"].str);
+               // Resolve 'Key not found: fileSystemInfo' when then item is a remote item
+               // https://github.com/abraunegg/onedrive/issues/11
+               if (isItemRemote(driveItem)) {
+                       item.mtime = SysTime.fromISOExtString(driveItem["remoteItem"]["fileSystemInfo"]["lastModifiedDateTime"].str);
+               } else {
+                       item.mtime = SysTime.fromISOExtString(driveItem["fileSystemInfo"]["lastModifiedDateTime"].str);
+               }
        }
 
        if (isItemFile(driveItem)) {
@@ -304,26 +310,53 @@
        {
                log.vlog("Applying changes of Path ID: " ~ id);
                JSONValue changes;
-               string syncFolderName;
                string deltaLink = itemdb.getDeltaLink(driveId, id);
-               JSONValue idDetails = onedrive.getPathDetailsById(id);
 
-               // Set the name of this folder
-               if ((idDetails["id"].str == id) && (isItemFolder(idDetails))){
-                       syncFolderName = idDetails["name"].str;
+               // Query the name of this folder id
+               string syncFolderName;
+               JSONValue idDetails = parseJSON("{}");
+               try {
+                       idDetails = onedrive.getPathDetailsById(driveId, id);
+               } catch (OneDriveException e) {
+                       if (e.httpStatusCode == 404) {
+                               // id was not found - possibly a remote (shared) folder
+                               log.vlog("No details returned for given Path ID");
+                               return;
+                       }
+               } 
+
+               // Get the name of this 'Path ID'
+               if (("id" in idDetails) != null) {
+                       // valid response from onedrive.getPathDetailsById(driveId, id) - a JSON item object present
+                       if ((idDetails["id"].str == id) && (isItemFolder(idDetails))){
+                               syncFolderName = encodeComponent(idDetails["name"].str);
+                       }
                }
-
+
                for (;;) {
+                       // Due to differences in OneDrive API's between personal and business we need to get changes only from defaultRootId
+                       // If we used the 'id' passed in & when using --single-directory with a business account we get:
+                       //      'HTTP request returned status code 501 (Not Implemented): view.delta can only be called on the root.'
+                       // To view changes correctly, we need to use the correct path id for the request
+                       const(char)[] idToQuery;
+                       if (driveId == defaultDriveId) {
+                               // The drive id matches our users default drive id
+                               idToQuery = defaultRootId.dup;
+                       } else {
+                               // The drive id does not match our users default drive id
+                               // Potentially the 'path id' we are requesting the details of is a Shared Folder (remote item)
+                               // Use the 'id' that was passed in
+                               idToQuery = id;
+                       }
+
                        try {
-                               // Due to differences in OneDrive API's between personal and business we need to get changes only from defaultRootId
-                               // If we used the 'id' passed in & when using --single-directory with a business account we get:
-                               //      'HTTP request returned status code 501 (Not Implemented): view.delta can only be called on the root.'
-                               // To view changes correctly, we need to use 'defaultRootId' 
-                               changes = onedrive.viewChangesById(driveId, defaultRootId, deltaLink);
+                               // Fetch the changes relative to the path id we want to query
+                               changes = onedrive.viewChangesById(driveId, idToQuery, deltaLink);
 
                        } catch (OneDriveException e) {
+                               // HTTP request returned status code 410 (The requested resource is no longer available at the server)
                                if (e.httpStatusCode == 410) {
-                                       log.vlog("Delta link expired, resyncing...");
+                                       log.vlog("Delta link expired, re-syncing...");
                                        deltaLink = null;
                                        continue;
                                }
@@ -339,9 +372,10 @@
 
                                if (e.httpStatusCode == 504) {
                                        // HTTP request returned status code 504 (Gateway Timeout)
-                                       // Retry
+                                       // Retry by calling applyDifferences() again
                                        //log.vlog("OneDrive returned a 'HTTP 504 - Gateway Timeout' - gracefully handling error");
-                                       changes = onedrive.viewChangesById(driveId, defaultRootId, deltaLink);
+                                       //changes = onedrive.viewChangesById(driveId, defaultRootId, deltaLink);
+                                       applyDifferences(driveId, defaultRootId);
                                }
 
                                else throw e;
@@ -354,12 +388,22 @@
                                // Thus we cannot name check for 'root' below on deleted items
                                if(!isItemDeleted(item)){
                                        // This is not a deleted item
-                                       // Test is this is the OneDrive Root?
+                                       // // Test is this is the OneDrive Users Root?
+                                       // Test is this a Shared Folder - which should be classified as a 'root'
                                        // Use the global's as initialised via init() rather than performing unnecessary additional HTTPS calls
-                                       if ((id == defaultRootId) && (item["name"].str == "root")) { // fix for https://github.com/skilion/onedrive/issues/269
+                                       if ((id == defaultRootId) && (item["name"].str == "root")) { 
                                                // This IS the OneDrive Root
                                                isRoot = true;
                                        }
+
+                                       // Test is this a Shared Folder - which should be classified as a 'root'
+                                       if (changeHasParentReferenceId(item)) {
+                                               // item contains parentReference key
+                                               string sharedDriveRootPath = "/drives/" ~ item["parentReference"]["driveId"].str ~ "/root:";
+                                               if (item["parentReference"]["path"].str == sharedDriveRootPath) {
+                                                       isRoot = true;
+                                               }
+                                       }
                                }
 
                                // How do we handle this change?
@@ -380,10 +424,11 @@
                                                // This is a corner edge case - https://github.com/skilion/onedrive/issues/341
                                                JSONValue oneDriveMovedNotDeleted;
                                                try {
-                                                       oneDriveMovedNotDeleted = onedrive.getPathDetailsById(item["id"].str);
+                                                       oneDriveMovedNotDeleted = onedrive.getPathDetailsById(driveId, item["id"].str);
                                                } catch (OneDriveException e) {
                                                        if (e.httpStatusCode == 404) {
                                                                // No .. that ID is GONE
+                                                               log.vlog("Remote change discarded - item cannot be found");
                                                                return;
                                                        } 
                                                }
```

**Comment by mcmtroffaes** [comment]
Sadly, with that patch I still see the same issue with truncated paths...

(Just to note: cutting & pasting patches is a pain (both for you and for me) - you can simply use a separate feature branch on git.)

**Comment by abraunegg** [comment]
OK .. that is weird as for OneDrive Personal all the folder names are 100% OK.

**Comment by abraunegg** [comment]
It was late at night for me & and didn't want to foul up 'master' - just created a branch for this issue

**Comment by mcmtroffaes** [comment]
Ok. I tested again just to make really sure that I didn't foul up the test somehow. However, names are still truncated. :-( This is OneDrive business, haven't tested with OneDrive personal.

**Comment by abraunegg** [comment]
I have tested this against OneDrive Business & OneDrive Personal:

https://github.com/abraunegg/onedrive/tree/Issue-%2311-and-%2317

* I am not getting any truncated files from OneDrive Business
* I am getting 'Shared Folders' syncing correctly from OneDrive Personal

Can you help test?

**Comment by mcmtroffaes** [comment]
Just tested it - works fine now! Many thanks for all your hard work to resolve this tricky issue!!

**Comment by abraunegg** [comment]
Thanks for testing

**Comment by abraunegg** [comment]
Once #11 has been verified as being resolved as well, will merge this into master

**Comment by abraunegg** [comment]
Resolved with https://github.com/abraunegg/onedrive/commit/17e5138b5a7aeb00e856e85b81818af6bfe0ddb9
