### ISSUE TITLE
JSONValue is not an object while uploading to OneDrive Business

### ISSUE THREAD

**Issue by 0x3333** [abraunegg/onedrive#464]
### Bug Report Details ###
While syncing after sometime, I get this error. I'm using master.

**Application and Operating System Details:**
*   OS: `Linux smb 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux`
*   Headless system
*   OneDrive Business
*   Application configuration: 
```onedrive version                    = v2.3.2-7-gea22d8f
Config path                         = .config/
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /srv/samba/OneDrive/
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|._*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = true
sync_list contents:
File Server
```

*   Curl Version: ```curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL```

**Complete Verbose Log Output**
(File name redacted, huge long one, just replaced the chars with X)

```bash
onedrive --version
onedrive v2.3.2-7-gea22d8f

onedrive --confdir "/srv/samba/OneDrive/.config" --synchronize --upload-only --verbose --verbose
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /root
[DEBUG] configDirName: CLI override to set configDirName to: /srv/samba/OneDrive/.config
Using Config Dir: /srv/samba/OneDrive/.config
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /srv/samba/OneDrive/
Initializing the OneDrive API ...
Opening the item database ...
[DEBUG] Using database file: /srv/samba/OneDrive/.config/items.sqlite3
All operations will be performed in: /srv/samba/OneDrive/
[DEBUG] Loading user configured sync_list file ...
[DEBUG] sync_list: File Server
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir:
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|._*
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!xxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Default Root ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Remaining Free Space: 1001916485857
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root

...

[DEBUG] Checking file: x/xxxxxxxxxxx/xxxxxxxxxxx/xxxxxxxxx/xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.pdf
Giving up on sync after three attempts: JSONValue is not an object
std.json.JSONException@std/json.d(306): JSONValue is not an object
----------------
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x497e7687]
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/exception.d:436 pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x497e7601]
??:? inout pure @property @trusted inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.objectNoRef() [0x49837e35]
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/json.d:645 const pure @safe const(std.json.JSONValue)* std.json.JSONValue.opBinaryRight!("in").opBinaryRight(immutable(char)[]) [0x497fec73]
src/sync.d:1891 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x4980ffbc]
src/sync.d:1579 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980ea18]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x4980e90f]
src/sync.d:1140 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x4980ce0d]
src/main.d:584 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x497fa519]
src/main.d:376 _Dmain [0x497f9939]
```

**Comment by abraunegg** [comment]
@0x3333 
Is this reproducible 100% of the time with this long path?

Can you run in `--verbose --verbose` mode to see what error response is being generated from OneDrive, as your log above does not indicate this.

**Comment by abraunegg** [comment]
@0x3333 
If easier - can you please send your **FULL** unredacted log file to support@mynas.com.au

**Comment by 0x3333** [comment]
The output is already using `--verbose` Twice. 

I can send, but there is only checks, not a single error message. My library is huge.

This error happens 100% of the time.

**Comment by abraunegg** [comment]
@0x3333 
Can you please follow these instructions: https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

Please send me via email the FULL log un redacted log (without the Authorization bearer) so I can work out WHY OneDrive is generating an error.

**Comment by norbusan** [comment]
Ahhh, I have seen this error, too ... but it is hard to trigger reproducibly, so I didn't really follow up with it. @0x3333 Can you reproduce this consistently?

**Comment by abraunegg** [comment]
PR #465 should resolve this

**Comment by abraunegg** [comment]
@0x3333 
Can you please try this PR to fix your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/465/head:pr465
git checkout pr465
make clean; make;
```

**Comment by 0x3333** [comment]
@norbusan yes, in my case, everytime I run the sync, it crashes. My library is really huge, don't know if this is a problem or not.
I run another time today, some files were uploaded, as they were modified by the users, and the problem persisted.
I'll try the PR and let you know.

**Comment by 0x3333** [comment]
I tried the PR, didn't work:
```
onedrive --version                                                                                                                                                                                                                                                       10:23:25
onedrive v2.3.2-8-g72931a1
```

```
Giving up on sync after three attempts: JSONValue is not an object
std.json.JSONException@std/json.d(278): JSONValue is not an object
----------------
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x19e84687]
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/exception.d:436 pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x19e84601]
??:? inout pure ref @property inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.object() [0x19ed4e0d]
src/sync.d:1891 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x19eacfa2]
src/sync.d:1579 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eaba18]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1140 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x19ea9e0d]
src/main.d:584 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x19e97519]
src/main.d:376 _Dmain [0x19e96939]
```

**Comment by 0x3333** [comment]
Here is the log, with nonnecessary info removed:

Command to clean log:
```
cat onedrive.log | grep -v "^Processing" | grep -v "^The .* has not changed" | grep -v '^\[DEBUG\] Checking ' | grep -v "^Skipping item - excluded by skip_file"
```

```
onedrive v2.3.2-8-g72931a1
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /root
[DEBUG] configDirName: CLI override to set configDirName to: /srv/samba/OneDrive/.config
Using Config Dir: /srv/samba/OneDrive/.config
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /srv/samba/OneDrive/
Initializing the OneDrive API ...
Opening the item database ...
[DEBUG] Using database file: /srv/samba/OneDrive/.config/items.sqlite3
All operations will be performed in: /srv/samba/OneDrive/
[DEBUG] Loading user configured sync_list file ...
[DEBUG] sync_list: File Server
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir:
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|._*
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!uMC2REDACTEDle_idHp_x3ppCdvzwXREDACTEDOLGf3
Default Root ID: 01RJREDACTEDW7725BZO354PWSELRRZ
Remaining Free Space: 1004078596035
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
The file last modified time has changed
The file content has changed
Uploading modified file REDACTED/04122019 Rev.xlsx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:11
[DEBUG] Adding to database: Item("b!uMC2REDACTEDle_idHp_x3ppCdvzwREDACTEDtuDiOLGf3", "01RJZH3NQ4REDACTED2PWQRJIVYHMKC", "04122019 Rev.xlsx", file, "\"{393B0C1C-4896-49CA-A7DA-114A2B83B142},12\"", "\"c:{393B0C1C-4896-49CA-A7DA-114A2B83B142},5\"", 2019-Apr-12 13:07:44Z, "01RJZH3NUX7AREDACTEDE3RA4XPRLZONRD", "", "", "jWS/BkUREDACTEDPEIMj/bVoULosY=", "", "")
done.
Uploading new items of .
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - path excluded by sync_list: ./REDACTED/Windows
Skipping item - path excluded by sync_list: ./REDACTED/Mac
Skipping item - path excluded by sync_list: ./REDACTED/Linux
Retry sync count: 1: JSONValue is not an object
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Uploading new items of .
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - path excluded by sync_list: ./REDACTED/Windows
Skipping item - path excluded by sync_list: ./REDACTED/Mac
Skipping item - path excluded by sync_list: ./REDACTED/Linux
Retry sync count: 2: JSONValue is not an object
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Uploading new items of .
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - invalid name (Microsoft Naming Convention): ./REDACTED/desktop.ini
Skipping item - path excluded by sync_list: ./REDACTED/Windows
Skipping item - path excluded by sync_list: ./REDACTED/Mac
Skipping item - path excluded by sync_list: ./REDACTED/Linux
Giving up on sync after three attempts: JSONValue is not an object
std.json.JSONException@std/json.d(278): JSONValue is not an object
----------------
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x19e84687]
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/exception.d:436 pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x19e84601]
??:? inout pure ref @property inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.object() [0x19ed4e0d]
src/sync.d:1891 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x19eacfa2]
src/sync.d:1579 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eaba18]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1571 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x19eab90f]
src/sync.d:1140 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x19ea9e0d]
src/main.d:584 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x19e97519]
src/main.d:376 _Dmain [0x19e96939]
```

**Comment by 0x3333** [comment]
I sent to support@mynas.com.au the log with http debug.

**Comment by 0x3333** [comment]
I analyzed the log with http debug, and it shows a `HTTP/1.1 401 Unauthorized` in a specific file. I tried removing it, and the error persist, even without this file on the OneDrive.
Should be this a error with the local sqlite database?

**Comment by 0x3333** [comment]
I removed the database, and started sync again, will take a while, IKYP.

**Comment by 0x3333** [comment]
Well, even with the database removed, the same issue, same error.

**Comment by abraunegg** [comment]
@0x3333 
Please can you rebuild your client with the updated PR - you should be running `v2.3.2-9-g1a9560e` when testing this against your issue.

**Comment by abraunegg** [comment]
@0x3333 
Can you please provide an update as to testing with the updated PR or the latest master

**Comment by 0x3333** [comment]
Sorry for the delay, but I'll be able to test tomorrow morning(GMT-3). I'll keep you posted.

**Comment by 0x3333** [comment]
Well, looks like it is working. It is still running(4 hours). As soon as it finishes, I'll let you know.

**Comment by abraunegg** [comment]
@0x3333 
Glad this is working. Any update on further progress?

**Comment by 0x3333** [comment]
Still, running... I believe it will take some time... I'll keep you posted.

**Comment by abraunegg** [comment]
@0x3333 
Given that it has been running for ~9hrs and I suspect that this is resolved, marking this bug as fixed

**Comment by abraunegg** [comment]
@0x3333 
Closing this out as most likely fully resolved

**Comment by 0x3333** [comment]
It is still running, probably fixed. Thanks.

**Comment by abraunegg** [comment]
The only logical explanation is:
* The path has some weird character or OneDrive keyword
* The filename has some weird character or OneDrive keyword

To diagnose further I would need:
* Full unredacted log
* The actual file
